# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_description', models.CharField(max_length=100)),
                ('video_duration', models.CharField(max_length=5)),
                ('video_location', models.CharField(max_length=100)),
                ('video_tags', models.CharField(max_length=100)),
            ],
        ),
    ]
