# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_duration',
            field=models.CharField(max_length=100),
        ),
    ]
